- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: check ram
      shell: free
    - name: Copy mysql server config file
      become: yes
      ansible.builtin.copy:
        src: mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify: Restart mysql

  handlers:
    - name: Restart mysql
      become: yes
      ansible.builtin.service:
        name: mysql
        state: restarted
