- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: check ram
      shell: free
      notify: Restart mysql

  handlers:
    - name: Restart mysql
      become: yes
      ansible.builtin.service:
        name: mysql
        state: restarted
