- hosts: all
  order: sorted
  vars_files:
    - vars.yml
  tasks:
    - name: check ram
      shell: free
    - name: dummy
      shell: echo {{ service }}
      register: dummy
    - debug: msg="{{ dummy.stdout }}"
    - name: Copy mysql server config file
      when: bind_address is defined
      become: yes
      template:
        src: mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify: Restart mysql

  handlers:
    - name: Restart mysql
      become: yes
      ansible.builtin.service:
        name: mysql
        state: restarted
