- hosts: all
  strategy: free
  order: sorted
  vars_files:
    - vars.yml
  tasks:
    - name: check ram
      shell: free
    - name: dummy
      shell: echo {{ service }}
      register: dummy
    - debug: msg="{{ dummy.stdout }}"
    - name: Copy mysql server config file
      when: bind_address is defined
      become: yes
      template:
        src: mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify:
        - Restart mysql
        - Restart replica
        - Show query result

  handlers:
    - name: Restart mysql
      become: yes
      ansible.builtin.service:
        name: mysql
        state: restarted
    - name: Restart replica
      become: yes
      community.mysql.mysql_query:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_db: db
        query: SELECT * FROM users
      register: query
    - name: Show query result
      debug: msg="{{ query.query_result }}"
